### ISSUE TITLE
[1.7.10] Crash with DragonAPI (org.spongepowered.asm.mixin.throwables.MixinApplyError: Re-entrance error)

### ISSUE THREAD

**Issue by aking4125** [Aizistral-Studios/Grimoire#3]
Hello,

I am receiving a crash upon startup. A crash report isn't generated so here is the .log file. Any ideas?

Possible conflict with [EndlessIDs](https://www.curseforge.com/minecraft/mc-mods/endlessids) and [SpongeMixins](https://www.curseforge.com/minecraft/mc-mods/spongemixins) I read your comment there stating 

"_Superseeded by [Grimoire API](https://www.curseforge.com/minecraft/mc-mods/grimoire-api)_"

However [AnimFix](https://www.curseforge.com/minecraft/mc-mods/animfix) requires SpongeMixins.

[fml-client-latest.log](https://github.com/FalsePattern/EndlessIDs/files/8477699/fml-client-latest.log)

The issue was also reported to EndlessIDs as well just in-case https://github.com/FalsePattern/EndlessIDs/issues/1

**Comment by Aizistral** [comment]
> However [AnimFix](https://www.curseforge.com/minecraft/mc-mods/animfix) requires SpongeMixins.

Functionally Grimoire can replace SpongeMixins as-is, but it doesn't help in this case since that mod declares explicit dependency on SpongeMixins specifically. There shouldn't be any issues solely from booting both Grimoire and SpongeMixins in modpack though.

From what I can see your particualar issue indeed resides on the side of EndlessID's, and their attempt to mess with classpath very early in coremod loading. They wouldn't need to do it at all if they switched to Grimoire. In any event, changes are neccessary on their side to fix this.

**Comment by aking4125** [comment]
Copy. I created an issue on the https://github.com/TCLProject/Biome-ID-Extender/issues/2 before this one as a precaution. Just thought I'd also bring it up here as well.

Thank you for the verification.

**Comment by FalsePattern** [comment]
I cleaned up the mixin logic of my mods, the latest versions no longer hard depend on spongemixins

**Comment by Aizistral** [comment]
Your implementation is... somewhat questionable still, but whatever gets the job done I guess.
